FROM paritytech/ci-linux:production as builder

RUN git clone https://github.com/substrate-developer-hub/substrate-parachain-template.git

RUN cd substrate-parachain-template &&\
  git checkout b32ee91 &&\
  cargo build --release
